spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/develhopedb
    username: test
    password: testpassword
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
